Typescript: add basic enum reflection
coursera/courier pull request #42
Opened 2017-01-16 23:02 UTC by eboto

WIP DO NOT MERGE

This change will add a `.all` property to all enum companion modules, making it possible to map over all possible values.

2017-01-16 23:51 UTC, eboto commented
@amory-coursera would appreciate a quick review on this one!

2017-01-16 23:56 UTC, amory-coursera requested changes
Looks good, with one small nit.

2017-01-16 23:56 UTC, amory-coursera commented on typescript-lite/generator/src/main/java/org/coursera/courier/tslite/TSSyntax.java
> +    /** Adds an underscore after the symbol name when escaping. e.g.: class becomes class$*/
nit: 'underscore' -> 'dollar sign'

2017-01-16 23:57 UTC, eboto commented on typescript-lite/generator/src/main/java/org/coursera/courier/tslite/TSSyntax.java
> +    /** Adds an underscore after the symbol name when escaping. e.g.: class becomes class$*/
:man_facepalming: 

Gonna look at that. Also I'm seeing a weird regression regarding docstrings.

2017-01-17 00:05 UTC, eboto commented
OK nice catch on the copy of that docstring.

Also the ts docstring regression exists in master too. I'm going to figure out where that regression came in, make a testcase, and fix it in a separate PR.

Feel free to merge this one...

2017-01-17 01:02 UTC, merged